//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureMoverGui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Datastore : global::System.Configuration.ApplicationSettingsBase {
        
        private static Datastore defaultInstance = ((Datastore)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Datastore())));
        
        public static Datastore Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsSerializeAs(global::System.Configuration.SettingsSerializeAs.Binary)]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAEAAAD/////AQAAAAAAAAAMAgAAAEZQaWN0dXJlTW92ZXJHdWksIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBAEAAACMAVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbUGljdHVyZU1vdmVyR3VpLlNpbXBsZUV2ZW50RGF0YSwgUGljdHVyZU1vdmVyR3VpLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dAwAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24EAAAhUGljdHVyZU1vdmVyR3VpLlNpbXBsZUV2ZW50RGF0YVtdAgAAAAgICQMAAAAAAAAAAAAAAAcDAAAAAAEAAAAAAAAABB9QaWN0dXJlTW92ZXJHdWkuU2ltcGxlRXZlbnREYXRhAgAAAAs=")]  // Binary value for an empty list of this object
        public System.Collections.Generic.List<SimpleEventData> EventList
        {
            get
            {
                return ((System.Collections.Generic.List<SimpleEventData>)(this["EventList"]));
            }
            set
            {
                this["EventList"] = value;
            }
        }
    }
}
