//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureMoverGui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Persistant : global::System.Configuration.ApplicationSettingsBase {
        
        private static Persistant defaultInstance = ((Persistant)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Persistant())));
        
        public static Persistant Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2022-03-01")]
        public global::System.DateTime LastMobilePull {
            get {
                return ((global::System.DateTime)(this["LastMobilePull"]));
            }
            set {
                this["LastMobilePull"] = value;
            }
        }
    }
}
