//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureMoverGui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Persistant : global::System.Configuration.ApplicationSettingsBase {
        
        private static Persistant defaultInstance = ((Persistant)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Persistant())));
        
        public static Persistant Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MediaDeviceName {
            get {
                return ((string)(this["MediaDeviceName"]));
            }
            set {
                this["MediaDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MediaDeviceSerialNr {
            get {
                return ((string)(this["MediaDeviceSerialNr"]));
            }
            set {
                this["MediaDeviceSerialNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemovableDeviceName {
            get {
                return ((string)(this["RemovableDeviceName"]));
            }
            set {
                this["RemovableDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemovableDeviceSerialNr {
            get {
                return ((string)(this["RemovableDeviceSerialNr"]));
            }
            set {
                this["RemovableDeviceSerialNr"] = value;
            }
        }
    }
}
